modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="pingusharveymarvel"
version="1.0.0"
displayName="Pingu And HarveylMT's: Marvels"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="CommnistPingu & HarveylMT"

[[dependencies.pingusharveymarvel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




